DEFINES = [
    "V8_DEPRECATION_WARNINGS",
    "__STDC_CONSTANT_MACROS",
    "__STDC_FORMAT_MACROS",
    "_DEBUG",
    "V8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64",
    "ENABLE_MINOR_MC",
    "V8_DEPRECATION_WARNINGS",
    "V8_IMMINENT_DEPRECATION_WARNINGS",
    "V8_CONCURRENT_MARKING",
    "V8_TARGET_ARCH_X64",
]

